version: '3.8'

services:
  claude-code-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-ui
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOME=/app/data
      - CLAUDE_CONFIG_DIR=/app/data/claude
      - WORKSPACE_DIR=/app/workspace
    volumes:
      # 持久化应用数据
      - claude_data:/app/data
      
      # Claude CLI 配置目录挂载 (读写权限，用于保存配置和会话)
      - ${CLAUDE_CONFIG_DIR:-~/.claude}:/app/data/claude
      
      # Claude CLI 主配置文件挂载
      - ${CLAUDE_JSON:-~/.claude.json}:/app/.claude.json
      
      # 代码工作区挂载 (读写权限，用于代码修改和项目管理)
      - ${WORKSPACE_DIR:-~/workspace}:/app/workspace
      
      # Git 配置挂载 (可选)
      - ${GIT_CONFIG:-~/.gitconfig}:/app/.gitconfig:ro
    restart: unless-stopped
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/auth/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: claude-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - claude-code-ui
    restart: unless-stopped
    networks:
      - claude-network
    profiles:
      - nginx

volumes:
  claude_data:
    driver: local

networks:
  claude-network:
    driver: bridge